apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccount: jenkins
      nodeSelector:
        dedicated: master
      containers:
        - name: jenkins
          image: kozhenkov/jenkins-docker:latest
          ports:
            - containerPort: 8080
            - containerPort: 50000
          volumeMounts:
            - mountPath: /var/jenkins_home
              name: jenkins-volume
            - mountPath: /var/run/docker.sock
              name: docker-sock-volume
            - mountPath: /bin/docker
              name: docker-bin
          resources:
            limits:
              cpu: "750m"
      volumes:
        - name: jenkins-volume
          hostPath:
            path: /data/jenkins
            type: Directory
        - name: docker-sock-volume
          hostPath:
            path: /var/run/docker.sock
            type: File
        - name: docker-bin
          hostPath:
            path: /usr/bin/docker
            type: File
